version: '3.3'

name: algafood-api
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'algafood'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - mysql
    ports:
      - '8081:80'
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD:
      PMA_HOST: mysql
    depends_on:
      - mysql